[lib]

[package]
name = "feagi-async"
version = "0.0.1"
edition = "2021"

[features]
default = [standard-tokio]
standard-tokio = ["dep:tokio"] # Standard OS implementations
wasm = ["dep:wasm-bindgen", "dep:js-sys"] # Web implementations
wasi = ["dep:wasm-rs-async-executor"] # Wasm but for local machines
# embedded-esp-32 = ["dep:embassy-executor"] # TODO Embedded support can come later


[dependencies]
tokio = {version = "1.48.0", optional = true, features = ["rt", "macros"]}

wasm-bindgen = { version = "0.2.106", optional = true }
js-sys = { version = "0.3.83", optional = true }

wasm-rs-async-executor = {version = "0.9.0", optional = true}

#embassy-executor = { version = "0.9.1", optional = true } # TODO Embedded support can come later