[package]
name = "feagi-serialization"
version = "0.0.1-beta.4"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Adds serialization and deserialization to select Feagi Data Structures."


[dependencies]
serde_json = { workspace = true }
byteorder = "1.5.0"
getrandom = "0.2"
feagi-structures = { version = "0.0.1-beta.4", path = "../feagi-structures" }
serde = { version = "1.0.228", features = ["derive"] }
